"""init

Revision ID: b32e3976f4bc
Revises: 
Create Date: 2021-12-27 23:10:53.912494

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "b32e3976f4bc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artist",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artist_id"), "artist", ["id"], unique=False)
    op.create_index(op.f("ix_artist_name"), "artist", ["name"], unique=False)
    op.create_table(
        "song",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_song_artist_id"), "song", ["artist_id"], unique=False)
    op.create_index(op.f("ix_song_id"), "song", ["id"], unique=False)
    op.create_index(op.f("ix_song_name"), "song", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_song_name"), table_name="song")
    op.drop_index(op.f("ix_song_id"), table_name="song")
    op.drop_index(op.f("ix_song_artist_id"), table_name="song")
    op.drop_table("song")
    op.drop_index(op.f("ix_artist_name"), table_name="artist")
    op.drop_index(op.f("ix_artist_id"), table_name="artist")
    op.drop_table("artist")
    # ### end Alembic commands ###
